macOS cleanup and generalization

diff --git a/base/macOS/config/dock b/base/macOS/config/dock
--- a/base/macOS/config/dock
+++ b/base/macOS/config/dock
@@ -1,19 +1,44 @@
 #!/usr/bin/env zsh
 
 __add_app_to_dock() {
-  # adds an application to macOS Dock
-  # usage: add_app_to_dock "Application Name" 
-  # example add_app_to_dock "Terminal"
+    app_name="${1}"
+    app_path=""
 
-  app_name="${1}"
-  launchservices_path="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"
-  app_path=$(${launchservices_path} -dump | grep -o "/.*${app_name}.app" | grep -v -E "Backups|Caches|TimeMachine|Temporary|/Volumes/${app_name}" | uniq | sort | head -n1)
-  if open -Ra "${app_path}"; then
-      echo "$app_path added to the Dock."
-      defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>${app_path}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
-  else
-      echo "ERROR: $1 not found." 1>&2
-  fi
+    # places to look for an application
+    declare -a system_paths=(
+    "/System/Applications"
+    "/System/Applications/Utilities"
+    "/System/Library/CoreServices"
+    "/Applications"
+    "$HOME/Applications"
+    );
+
+    # check the paths for the app
+    for spath in "${system_paths[@]}"; do
+        app=$(ls "${spath}" | grep -o "${app_name}.app" | uniq | sort | head -n1)
+        if [[ -n "${app}" ]]; then
+            app_path="${spath}/${app}"
+        fi
+    done
+
+    if open -Ra "${app_path}"; then
+        echo "Dock: $app_path added to the Dock."
+
+        defaults write com.apple.dock persistent-apps -array-add "<dict>
+            <key>tile-data</key>
+            <dict>
+                <key>file-data</key>
+                <dict>
+                    <key>_CFURLString</key>
+                    <string>${app_path}</string>
+                    <key>_CFURLStringType</key>
+                    <integer>0</integer>
+                </dict>
+            </dict>
+        </dict>"
+    else
+        echo "ERROR: Application $1 not found." 1>&2
+    fi
 }
 
 __add_spacer_to_dock() {
@@ -34,17 +59,24 @@ __reset_dock() {
 # WARNING: permanently clears existing dock
 __clear_dock
 
+__add_app_to_dock "Finder"
+__add_app_to_dock "Launchpad"
 __add_app_to_dock "System Preferences"
+__add_spacer_to_dock
 __add_app_to_dock "Activity Monitor"
 __add_app_to_dock "Console"
 __add_app_to_dock "Terminal"
+__add_app_to_dock "Wireshark"
 __add_spacer_to_dock
 __add_app_to_dock "Safari"
 __add_app_to_dock "Mail"
 __add_app_to_dock "Calendar"
+__add_app_to_dock "Things3"
+__add_app_to_dock "Messages"
 __add_app_to_dock "Music"
 __add_app_to_dock "Books"
 __add_app_to_dock "App Store"
 __add_spacer_to_dock
+__add_app_to_dock "Shadow"
 
 killall Dock
